name: artieri_et_al
channels:
  - bioconda
dependencies:
  - nomkl==1.0
  - python==2.7.12
  - pymc==2.3.6
  - numpy==1.11.2
  - pandas==0.19.1
  - scipy==0.18.1
  - matplotlib==1.5.1
  - scikit-learn==0.18.1
